all: false
template: testify
formatter: goimports
log-level: info
force-file-write: true

pkgname: mocks
structname: "{{.InterfaceName}}"

template-data:
  unroll-variadic: true

packages:
  github.com/horizoonn/factory-platform/assembly/internal/service/assembly:
    config:
      dir: "assembly/internal/service/mocks"
      filename: "mock_assembly_service.go"
    interfaces:
      ShipAssembledOutbox:

  github.com/horizoonn/factory-platform/assembly/internal/api/kafka/orderpaid:
    config:
      dir: "assembly/internal/service/mocks"
      filename: "mock_order_paid_handler.go"
    interfaces:
      AssemblyService:

  github.com/horizoonn/factory-platform/assembly/internal/outbox/dispatcher:
    config:
      dir: "assembly/internal/service/mocks"
      filename: "mock_outbox_dispatcher.go"
    interfaces:
      Repository:
      Producer:

  github.com/horizoonn/factory-platform/order/internal/service/order:
    config:
      dir: "order/internal/service/mocks"
      filename: "mock_order_service.go"
    interfaces:
      Repository:
      InventoryClient:
      PaymentClient:

  github.com/horizoonn/factory-platform/inventory/internal/service/part:
    config:
      dir: "inventory/internal/service/mocks"
      filename: "mock_part_service.go"
    interfaces:
      Repository:
