// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/google/uuid"
	"github.com/horizoonn/factory-platform/assembly/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewShipAssembledOutbox creates a new instance of ShipAssembledOutbox. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewShipAssembledOutbox(t interface {
	mock.TestingT
	Cleanup(func())
}) *ShipAssembledOutbox {
	mock := &ShipAssembledOutbox{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ShipAssembledOutbox is an autogenerated mock type for the ShipAssembledOutbox type
type ShipAssembledOutbox struct {
	mock.Mock
}

type ShipAssembledOutbox_Expecter struct {
	mock *mock.Mock
}

func (_m *ShipAssembledOutbox) EXPECT() *ShipAssembledOutbox_Expecter {
	return &ShipAssembledOutbox_Expecter{mock: &_m.Mock}
}

// EnqueueShipAssembled provides a mock function for the type ShipAssembledOutbox
func (_mock *ShipAssembledOutbox) EnqueueShipAssembled(ctx context.Context, sourceEventID uuid.UUID, event domain.ShipAssembledEvent) (bool, error) {
	ret := _mock.Called(ctx, sourceEventID, event)

	if len(ret) == 0 {
		panic("no return value specified for EnqueueShipAssembled")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, domain.ShipAssembledEvent) (bool, error)); ok {
		return returnFunc(ctx, sourceEventID, event)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, domain.ShipAssembledEvent) bool); ok {
		r0 = returnFunc(ctx, sourceEventID, event)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, domain.ShipAssembledEvent) error); ok {
		r1 = returnFunc(ctx, sourceEventID, event)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ShipAssembledOutbox_EnqueueShipAssembled_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnqueueShipAssembled'
type ShipAssembledOutbox_EnqueueShipAssembled_Call struct {
	*mock.Call
}

// EnqueueShipAssembled is a helper method to define mock.On call
//   - ctx context.Context
//   - sourceEventID uuid.UUID
//   - event domain.ShipAssembledEvent
func (_e *ShipAssembledOutbox_Expecter) EnqueueShipAssembled(ctx any, sourceEventID any, event any) *ShipAssembledOutbox_EnqueueShipAssembled_Call {
	return &ShipAssembledOutbox_EnqueueShipAssembled_Call{Call: _e.mock.On("EnqueueShipAssembled", ctx, sourceEventID, event)}
}

func (_c *ShipAssembledOutbox_EnqueueShipAssembled_Call) Run(run func(ctx context.Context, sourceEventID uuid.UUID, event domain.ShipAssembledEvent)) *ShipAssembledOutbox_EnqueueShipAssembled_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 domain.ShipAssembledEvent
		if args[2] != nil {
			arg2 = args[2].(domain.ShipAssembledEvent)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ShipAssembledOutbox_EnqueueShipAssembled_Call) Return(b bool, err error) *ShipAssembledOutbox_EnqueueShipAssembled_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *ShipAssembledOutbox_EnqueueShipAssembled_Call) RunAndReturn(run func(ctx context.Context, sourceEventID uuid.UUID, event domain.ShipAssembledEvent) (bool, error)) *ShipAssembledOutbox_EnqueueShipAssembled_Call {
	_c.Call.Return(run)
	return _c
}
