// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/horizoonn/factory-platform/assembly/internal/domain"
	"github.com/horizoonn/factory-platform/assembly/internal/outbox"
	mock "github.com/stretchr/testify/mock"
)

// NewOutbox creates a new instance of Outbox. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOutbox(t interface {
	mock.TestingT
	Cleanup(func())
}) *Outbox {
	mock := &Outbox{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Outbox is an autogenerated mock type for the Outbox type
type Outbox struct {
	mock.Mock
}

type Outbox_Expecter struct {
	mock *mock.Mock
}

func (_m *Outbox) EXPECT() *Outbox_Expecter {
	return &Outbox_Expecter{mock: &_m.Mock}
}

// Enqueue provides a mock function for the type Outbox
func (_mock *Outbox) Enqueue(ctx context.Context, event outbox.Event) (bool, error) {
	ret := _mock.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for Enqueue")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, outbox.Event) (bool, error)); ok {
		return returnFunc(ctx, event)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, outbox.Event) bool); ok {
		r0 = returnFunc(ctx, event)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, outbox.Event) error); ok {
		r1 = returnFunc(ctx, event)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Outbox_Enqueue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Enqueue'
type Outbox_Enqueue_Call struct {
	*mock.Call
}

// Enqueue is a helper method to define mock.On call
//   - ctx context.Context
//   - event outbox.Event
func (_e *Outbox_Expecter) Enqueue(ctx any, event any) *Outbox_Enqueue_Call {
	return &Outbox_Enqueue_Call{Call: _e.mock.On("Enqueue", ctx, event)}
}

func (_c *Outbox_Enqueue_Call) Run(run func(ctx context.Context, event outbox.Event)) *Outbox_Enqueue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 outbox.Event
		if args[1] != nil {
			arg1 = args[1].(outbox.Event)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Outbox_Enqueue_Call) Return(b bool, err error) *Outbox_Enqueue_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *Outbox_Enqueue_Call) RunAndReturn(run func(ctx context.Context, event outbox.Event) (bool, error)) *Outbox_Enqueue_Call {
	_c.Call.Return(run)
	return _c
}

// NewShipAssembledEncoder creates a new instance of ShipAssembledEncoder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewShipAssembledEncoder(t interface {
	mock.TestingT
	Cleanup(func())
}) *ShipAssembledEncoder {
	mock := &ShipAssembledEncoder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ShipAssembledEncoder is an autogenerated mock type for the ShipAssembledEncoder type
type ShipAssembledEncoder struct {
	mock.Mock
}

type ShipAssembledEncoder_Expecter struct {
	mock *mock.Mock
}

func (_m *ShipAssembledEncoder) EXPECT() *ShipAssembledEncoder_Expecter {
	return &ShipAssembledEncoder_Expecter{mock: &_m.Mock}
}

// Encode provides a mock function for the type ShipAssembledEncoder
func (_mock *ShipAssembledEncoder) Encode(event domain.ShipAssembledEvent) (outbox.Event, error) {
	ret := _mock.Called(event)

	if len(ret) == 0 {
		panic("no return value specified for Encode")
	}

	var r0 outbox.Event
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(domain.ShipAssembledEvent) (outbox.Event, error)); ok {
		return returnFunc(event)
	}
	if returnFunc, ok := ret.Get(0).(func(domain.ShipAssembledEvent) outbox.Event); ok {
		r0 = returnFunc(event)
	} else {
		r0 = ret.Get(0).(outbox.Event)
	}
	if returnFunc, ok := ret.Get(1).(func(domain.ShipAssembledEvent) error); ok {
		r1 = returnFunc(event)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ShipAssembledEncoder_Encode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Encode'
type ShipAssembledEncoder_Encode_Call struct {
	*mock.Call
}

// Encode is a helper method to define mock.On call
//   - event domain.ShipAssembledEvent
func (_e *ShipAssembledEncoder_Expecter) Encode(event any) *ShipAssembledEncoder_Encode_Call {
	return &ShipAssembledEncoder_Encode_Call{Call: _e.mock.On("Encode", event)}
}

func (_c *ShipAssembledEncoder_Encode_Call) Run(run func(event domain.ShipAssembledEvent)) *ShipAssembledEncoder_Encode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 domain.ShipAssembledEvent
		if args[0] != nil {
			arg0 = args[0].(domain.ShipAssembledEvent)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ShipAssembledEncoder_Encode_Call) Return(event1 outbox.Event, err error) *ShipAssembledEncoder_Encode_Call {
	_c.Call.Return(event1, err)
	return _c
}

func (_c *ShipAssembledEncoder_Encode_Call) RunAndReturn(run func(event domain.ShipAssembledEvent) (outbox.Event, error)) *ShipAssembledEncoder_Encode_Call {
	_c.Call.Return(run)
	return _c
}
