// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/horizoonn/factory-platform/assembly/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewAssemblyService creates a new instance of AssemblyService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAssemblyService(t interface {
	mock.TestingT
	Cleanup(func())
}) *AssemblyService {
	mock := &AssemblyService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// AssemblyService is an autogenerated mock type for the AssemblyService type
type AssemblyService struct {
	mock.Mock
}

type AssemblyService_Expecter struct {
	mock *mock.Mock
}

func (_m *AssemblyService) EXPECT() *AssemblyService_Expecter {
	return &AssemblyService_Expecter{mock: &_m.Mock}
}

// Assemble provides a mock function for the type AssemblyService
func (_mock *AssemblyService) Assemble(ctx context.Context, event domain.OrderPaidEvent) error {
	ret := _mock.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for Assemble")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.OrderPaidEvent) error); ok {
		r0 = returnFunc(ctx, event)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// AssemblyService_Assemble_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Assemble'
type AssemblyService_Assemble_Call struct {
	*mock.Call
}

// Assemble is a helper method to define mock.On call
//   - ctx context.Context
//   - event domain.OrderPaidEvent
func (_e *AssemblyService_Expecter) Assemble(ctx any, event any) *AssemblyService_Assemble_Call {
	return &AssemblyService_Assemble_Call{Call: _e.mock.On("Assemble", ctx, event)}
}

func (_c *AssemblyService_Assemble_Call) Run(run func(ctx context.Context, event domain.OrderPaidEvent)) *AssemblyService_Assemble_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.OrderPaidEvent
		if args[1] != nil {
			arg1 = args[1].(domain.OrderPaidEvent)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AssemblyService_Assemble_Call) Return(err error) *AssemblyService_Assemble_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *AssemblyService_Assemble_Call) RunAndReturn(run func(ctx context.Context, event domain.OrderPaidEvent) error) *AssemblyService_Assemble_Call {
	_c.Call.Return(run)
	return _c
}
