// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/horizoonn/factory-platform/assembly/internal/outbox"
	"github.com/horizoonn/factory-platform/platform/pkg/kafka"
	mock "github.com/stretchr/testify/mock"
)

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

type Repository_Expecter struct {
	mock *mock.Mock
}

func (_m *Repository) EXPECT() *Repository_Expecter {
	return &Repository_Expecter{mock: &_m.Mock}
}

// ClaimOne provides a mock function for the type Repository
func (_mock *Repository) ClaimOne(ctx context.Context, workerID string, leaseDuration time.Duration) (outbox.Event, bool, error) {
	ret := _mock.Called(ctx, workerID, leaseDuration)

	if len(ret) == 0 {
		panic("no return value specified for ClaimOne")
	}

	var r0 outbox.Event
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Duration) (outbox.Event, bool, error)); ok {
		return returnFunc(ctx, workerID, leaseDuration)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Duration) outbox.Event); ok {
		r0 = returnFunc(ctx, workerID, leaseDuration)
	} else {
		r0 = ret.Get(0).(outbox.Event)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, time.Duration) bool); ok {
		r1 = returnFunc(ctx, workerID, leaseDuration)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, time.Duration) error); ok {
		r2 = returnFunc(ctx, workerID, leaseDuration)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// Repository_ClaimOne_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClaimOne'
type Repository_ClaimOne_Call struct {
	*mock.Call
}

// ClaimOne is a helper method to define mock.On call
//   - ctx context.Context
//   - workerID string
//   - leaseDuration time.Duration
func (_e *Repository_Expecter) ClaimOne(ctx any, workerID any, leaseDuration any) *Repository_ClaimOne_Call {
	return &Repository_ClaimOne_Call{Call: _e.mock.On("ClaimOne", ctx, workerID, leaseDuration)}
}

func (_c *Repository_ClaimOne_Call) Run(run func(ctx context.Context, workerID string, leaseDuration time.Duration)) *Repository_ClaimOne_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Duration
		if args[2] != nil {
			arg2 = args[2].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Repository_ClaimOne_Call) Return(event outbox.Event, b bool, err error) *Repository_ClaimOne_Call {
	_c.Call.Return(event, b, err)
	return _c
}

func (_c *Repository_ClaimOne_Call) RunAndReturn(run func(ctx context.Context, workerID string, leaseDuration time.Duration) (outbox.Event, bool, error)) *Repository_ClaimOne_Call {
	_c.Call.Return(run)
	return _c
}

// MarkFailed provides a mock function for the type Repository
func (_mock *Repository) MarkFailed(ctx context.Context, workerID string, eventID uuid.UUID, lastError string) error {
	ret := _mock.Called(ctx, workerID, eventID, lastError)

	if len(ret) == 0 {
		panic("no return value specified for MarkFailed")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uuid.UUID, string) error); ok {
		r0 = returnFunc(ctx, workerID, eventID, lastError)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Repository_MarkFailed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkFailed'
type Repository_MarkFailed_Call struct {
	*mock.Call
}

// MarkFailed is a helper method to define mock.On call
//   - ctx context.Context
//   - workerID string
//   - eventID uuid.UUID
//   - lastError string
func (_e *Repository_Expecter) MarkFailed(ctx any, workerID any, eventID any, lastError any) *Repository_MarkFailed_Call {
	return &Repository_MarkFailed_Call{Call: _e.mock.On("MarkFailed", ctx, workerID, eventID, lastError)}
}

func (_c *Repository_MarkFailed_Call) Run(run func(ctx context.Context, workerID string, eventID uuid.UUID, lastError string)) *Repository_MarkFailed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *Repository_MarkFailed_Call) Return(err error) *Repository_MarkFailed_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Repository_MarkFailed_Call) RunAndReturn(run func(ctx context.Context, workerID string, eventID uuid.UUID, lastError string) error) *Repository_MarkFailed_Call {
	_c.Call.Return(run)
	return _c
}

// MarkPublished provides a mock function for the type Repository
func (_mock *Repository) MarkPublished(ctx context.Context, workerID string, eventID uuid.UUID) error {
	ret := _mock.Called(ctx, workerID, eventID)

	if len(ret) == 0 {
		panic("no return value specified for MarkPublished")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, workerID, eventID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Repository_MarkPublished_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkPublished'
type Repository_MarkPublished_Call struct {
	*mock.Call
}

// MarkPublished is a helper method to define mock.On call
//   - ctx context.Context
//   - workerID string
//   - eventID uuid.UUID
func (_e *Repository_Expecter) MarkPublished(ctx any, workerID any, eventID any) *Repository_MarkPublished_Call {
	return &Repository_MarkPublished_Call{Call: _e.mock.On("MarkPublished", ctx, workerID, eventID)}
}

func (_c *Repository_MarkPublished_Call) Run(run func(ctx context.Context, workerID string, eventID uuid.UUID)) *Repository_MarkPublished_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Repository_MarkPublished_Call) Return(err error) *Repository_MarkPublished_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Repository_MarkPublished_Call) RunAndReturn(run func(ctx context.Context, workerID string, eventID uuid.UUID) error) *Repository_MarkPublished_Call {
	_c.Call.Return(run)
	return _c
}

// Reschedule provides a mock function for the type Repository
func (_mock *Repository) Reschedule(ctx context.Context, workerID string, eventID uuid.UUID, nextAttemptAt time.Time, lastError string) error {
	ret := _mock.Called(ctx, workerID, eventID, nextAttemptAt, lastError)

	if len(ret) == 0 {
		panic("no return value specified for Reschedule")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uuid.UUID, time.Time, string) error); ok {
		r0 = returnFunc(ctx, workerID, eventID, nextAttemptAt, lastError)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Repository_Reschedule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reschedule'
type Repository_Reschedule_Call struct {
	*mock.Call
}

// Reschedule is a helper method to define mock.On call
//   - ctx context.Context
//   - workerID string
//   - eventID uuid.UUID
//   - nextAttemptAt time.Time
//   - lastError string
func (_e *Repository_Expecter) Reschedule(ctx any, workerID any, eventID any, nextAttemptAt any, lastError any) *Repository_Reschedule_Call {
	return &Repository_Reschedule_Call{Call: _e.mock.On("Reschedule", ctx, workerID, eventID, nextAttemptAt, lastError)}
}

func (_c *Repository_Reschedule_Call) Run(run func(ctx context.Context, workerID string, eventID uuid.UUID, nextAttemptAt time.Time, lastError string)) *Repository_Reschedule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *Repository_Reschedule_Call) Return(err error) *Repository_Reschedule_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Repository_Reschedule_Call) RunAndReturn(run func(ctx context.Context, workerID string, eventID uuid.UUID, nextAttemptAt time.Time, lastError string) error) *Repository_Reschedule_Call {
	_c.Call.Return(run)
	return _c
}

// NewProducer creates a new instance of Producer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProducer(t interface {
	mock.TestingT
	Cleanup(func())
}) *Producer {
	mock := &Producer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Producer is an autogenerated mock type for the Producer type
type Producer struct {
	mock.Mock
}

type Producer_Expecter struct {
	mock *mock.Mock
}

func (_m *Producer) EXPECT() *Producer_Expecter {
	return &Producer_Expecter{mock: &_m.Mock}
}

// Publish provides a mock function for the type Producer
func (_mock *Producer) Publish(ctx context.Context, topic string, msg kafka.Message) error {
	ret := _mock.Called(ctx, topic, msg)

	if len(ret) == 0 {
		panic("no return value specified for Publish")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, kafka.Message) error); ok {
		r0 = returnFunc(ctx, topic, msg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Producer_Publish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Publish'
type Producer_Publish_Call struct {
	*mock.Call
}

// Publish is a helper method to define mock.On call
//   - ctx context.Context
//   - topic string
//   - msg kafka.Message
func (_e *Producer_Expecter) Publish(ctx any, topic any, msg any) *Producer_Publish_Call {
	return &Producer_Publish_Call{Call: _e.mock.On("Publish", ctx, topic, msg)}
}

func (_c *Producer_Publish_Call) Run(run func(ctx context.Context, topic string, msg kafka.Message)) *Producer_Publish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 kafka.Message
		if args[2] != nil {
			arg2 = args[2].(kafka.Message)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Producer_Publish_Call) Return(err error) *Producer_Publish_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Producer_Publish_Call) RunAndReturn(run func(ctx context.Context, topic string, msg kafka.Message) error) *Producer_Publish_Call {
	_c.Call.Return(run)
	return _c
}
