// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/google/uuid"
	"github.com/horizoonn/factory-platform/inventory/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

type Repository_Expecter struct {
	mock *mock.Mock
}

func (_m *Repository) EXPECT() *Repository_Expecter {
	return &Repository_Expecter{mock: &_m.Mock}
}

// GetPart provides a mock function for the type Repository
func (_mock *Repository) GetPart(ctx context.Context, id uuid.UUID) (domain.Part, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetPart")
	}

	var r0 domain.Part
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (domain.Part, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) domain.Part); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.Part)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Repository_GetPart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPart'
type Repository_GetPart_Call struct {
	*mock.Call
}

// GetPart is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *Repository_Expecter) GetPart(ctx any, id any) *Repository_GetPart_Call {
	return &Repository_GetPart_Call{Call: _e.mock.On("GetPart", ctx, id)}
}

func (_c *Repository_GetPart_Call) Run(run func(ctx context.Context, id uuid.UUID)) *Repository_GetPart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Repository_GetPart_Call) Return(part domain.Part, err error) *Repository_GetPart_Call {
	_c.Call.Return(part, err)
	return _c
}

func (_c *Repository_GetPart_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (domain.Part, error)) *Repository_GetPart_Call {
	_c.Call.Return(run)
	return _c
}

// ListParts provides a mock function for the type Repository
func (_mock *Repository) ListParts(ctx context.Context, filter domain.PartsFilter) ([]domain.Part, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for ListParts")
	}

	var r0 []domain.Part
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.PartsFilter) ([]domain.Part, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.PartsFilter) []domain.Part); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Part)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.PartsFilter) error); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Repository_ListParts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListParts'
type Repository_ListParts_Call struct {
	*mock.Call
}

// ListParts is a helper method to define mock.On call
//   - ctx context.Context
//   - filter domain.PartsFilter
func (_e *Repository_Expecter) ListParts(ctx any, filter any) *Repository_ListParts_Call {
	return &Repository_ListParts_Call{Call: _e.mock.On("ListParts", ctx, filter)}
}

func (_c *Repository_ListParts_Call) Run(run func(ctx context.Context, filter domain.PartsFilter)) *Repository_ListParts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.PartsFilter
		if args[1] != nil {
			arg1 = args[1].(domain.PartsFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Repository_ListParts_Call) Return(parts []domain.Part, err error) *Repository_ListParts_Call {
	_c.Call.Return(parts, err)
	return _c
}

func (_c *Repository_ListParts_Call) RunAndReturn(run func(ctx context.Context, filter domain.PartsFilter) ([]domain.Part, error)) *Repository_ListParts_Call {
	_c.Call.Return(run)
	return _c
}
