// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/horizoonn/factory-platform/order/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewOrderService creates a new instance of OrderService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderService(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderService {
	mock := &OrderService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// OrderService is an autogenerated mock type for the OrderService type
type OrderService struct {
	mock.Mock
}

type OrderService_Expecter struct {
	mock *mock.Mock
}

func (_m *OrderService) EXPECT() *OrderService_Expecter {
	return &OrderService_Expecter{mock: &_m.Mock}
}

// CompleteOrder provides a mock function for the type OrderService
func (_mock *OrderService) CompleteOrder(ctx context.Context, event domain.ShipAssembledEvent) error {
	ret := _mock.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for CompleteOrder")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ShipAssembledEvent) error); ok {
		r0 = returnFunc(ctx, event)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// OrderService_CompleteOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CompleteOrder'
type OrderService_CompleteOrder_Call struct {
	*mock.Call
}

// CompleteOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - event domain.ShipAssembledEvent
func (_e *OrderService_Expecter) CompleteOrder(ctx any, event any) *OrderService_CompleteOrder_Call {
	return &OrderService_CompleteOrder_Call{Call: _e.mock.On("CompleteOrder", ctx, event)}
}

func (_c *OrderService_CompleteOrder_Call) Run(run func(ctx context.Context, event domain.ShipAssembledEvent)) *OrderService_CompleteOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.ShipAssembledEvent
		if args[1] != nil {
			arg1 = args[1].(domain.ShipAssembledEvent)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *OrderService_CompleteOrder_Call) Return(err error) *OrderService_CompleteOrder_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *OrderService_CompleteOrder_Call) RunAndReturn(run func(ctx context.Context, event domain.ShipAssembledEvent) error) *OrderService_CompleteOrder_Call {
	_c.Call.Return(run)
	return _c
}
