// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/google/uuid"
	"github.com/horizoonn/factory-platform/order/internal/client/dto"
	"github.com/horizoonn/factory-platform/order/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

type Repository_Expecter struct {
	mock *mock.Mock
}

func (_m *Repository) EXPECT() *Repository_Expecter {
	return &Repository_Expecter{mock: &_m.Mock}
}

// CreateOrder provides a mock function for the type Repository
func (_mock *Repository) CreateOrder(ctx context.Context, order domain.Order) (domain.Order, error) {
	ret := _mock.Called(ctx, order)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrder")
	}

	var r0 domain.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Order) (domain.Order, error)); ok {
		return returnFunc(ctx, order)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Order) domain.Order); ok {
		r0 = returnFunc(ctx, order)
	} else {
		r0 = ret.Get(0).(domain.Order)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.Order) error); ok {
		r1 = returnFunc(ctx, order)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Repository_CreateOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrder'
type Repository_CreateOrder_Call struct {
	*mock.Call
}

// CreateOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - order domain.Order
func (_e *Repository_Expecter) CreateOrder(ctx any, order any) *Repository_CreateOrder_Call {
	return &Repository_CreateOrder_Call{Call: _e.mock.On("CreateOrder", ctx, order)}
}

func (_c *Repository_CreateOrder_Call) Run(run func(ctx context.Context, order domain.Order)) *Repository_CreateOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Order
		if args[1] != nil {
			arg1 = args[1].(domain.Order)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Repository_CreateOrder_Call) Return(order1 domain.Order, err error) *Repository_CreateOrder_Call {
	_c.Call.Return(order1, err)
	return _c
}

func (_c *Repository_CreateOrder_Call) RunAndReturn(run func(ctx context.Context, order domain.Order) (domain.Order, error)) *Repository_CreateOrder_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrder provides a mock function for the type Repository
func (_mock *Repository) GetOrder(ctx context.Context, id uuid.UUID) (domain.Order, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetOrder")
	}

	var r0 domain.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (domain.Order, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) domain.Order); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.Order)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Repository_GetOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrder'
type Repository_GetOrder_Call struct {
	*mock.Call
}

// GetOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *Repository_Expecter) GetOrder(ctx any, id any) *Repository_GetOrder_Call {
	return &Repository_GetOrder_Call{Call: _e.mock.On("GetOrder", ctx, id)}
}

func (_c *Repository_GetOrder_Call) Run(run func(ctx context.Context, id uuid.UUID)) *Repository_GetOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Repository_GetOrder_Call) Return(order domain.Order, err error) *Repository_GetOrder_Call {
	_c.Call.Return(order, err)
	return _c
}

func (_c *Repository_GetOrder_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (domain.Order, error)) *Repository_GetOrder_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateOrder provides a mock function for the type Repository
func (_mock *Repository) UpdateOrder(ctx context.Context, order domain.Order) (domain.Order, error) {
	ret := _mock.Called(ctx, order)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOrder")
	}

	var r0 domain.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Order) (domain.Order, error)); ok {
		return returnFunc(ctx, order)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Order) domain.Order); ok {
		r0 = returnFunc(ctx, order)
	} else {
		r0 = ret.Get(0).(domain.Order)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.Order) error); ok {
		r1 = returnFunc(ctx, order)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Repository_UpdateOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateOrder'
type Repository_UpdateOrder_Call struct {
	*mock.Call
}

// UpdateOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - order domain.Order
func (_e *Repository_Expecter) UpdateOrder(ctx any, order any) *Repository_UpdateOrder_Call {
	return &Repository_UpdateOrder_Call{Call: _e.mock.On("UpdateOrder", ctx, order)}
}

func (_c *Repository_UpdateOrder_Call) Run(run func(ctx context.Context, order domain.Order)) *Repository_UpdateOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Order
		if args[1] != nil {
			arg1 = args[1].(domain.Order)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Repository_UpdateOrder_Call) Return(order1 domain.Order, err error) *Repository_UpdateOrder_Call {
	_c.Call.Return(order1, err)
	return _c
}

func (_c *Repository_UpdateOrder_Call) RunAndReturn(run func(ctx context.Context, order domain.Order) (domain.Order, error)) *Repository_UpdateOrder_Call {
	_c.Call.Return(run)
	return _c
}

// NewInventoryClient creates a new instance of InventoryClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInventoryClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *InventoryClient {
	mock := &InventoryClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// InventoryClient is an autogenerated mock type for the InventoryClient type
type InventoryClient struct {
	mock.Mock
}

type InventoryClient_Expecter struct {
	mock *mock.Mock
}

func (_m *InventoryClient) EXPECT() *InventoryClient_Expecter {
	return &InventoryClient_Expecter{mock: &_m.Mock}
}

// ListParts provides a mock function for the type InventoryClient
func (_mock *InventoryClient) ListParts(ctx context.Context, partIDs []uuid.UUID) ([]domain.Part, error) {
	ret := _mock.Called(ctx, partIDs)

	if len(ret) == 0 {
		panic("no return value specified for ListParts")
	}

	var r0 []domain.Part
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID) ([]domain.Part, error)); ok {
		return returnFunc(ctx, partIDs)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID) []domain.Part); ok {
		r0 = returnFunc(ctx, partIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Part)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []uuid.UUID) error); ok {
		r1 = returnFunc(ctx, partIDs)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// InventoryClient_ListParts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListParts'
type InventoryClient_ListParts_Call struct {
	*mock.Call
}

// ListParts is a helper method to define mock.On call
//   - ctx context.Context
//   - partIDs []uuid.UUID
func (_e *InventoryClient_Expecter) ListParts(ctx any, partIDs any) *InventoryClient_ListParts_Call {
	return &InventoryClient_ListParts_Call{Call: _e.mock.On("ListParts", ctx, partIDs)}
}

func (_c *InventoryClient_ListParts_Call) Run(run func(ctx context.Context, partIDs []uuid.UUID)) *InventoryClient_ListParts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []uuid.UUID
		if args[1] != nil {
			arg1 = args[1].([]uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *InventoryClient_ListParts_Call) Return(parts []domain.Part, err error) *InventoryClient_ListParts_Call {
	_c.Call.Return(parts, err)
	return _c
}

func (_c *InventoryClient_ListParts_Call) RunAndReturn(run func(ctx context.Context, partIDs []uuid.UUID) ([]domain.Part, error)) *InventoryClient_ListParts_Call {
	_c.Call.Return(run)
	return _c
}

// NewPaymentClient creates a new instance of PaymentClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPaymentClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *PaymentClient {
	mock := &PaymentClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// PaymentClient is an autogenerated mock type for the PaymentClient type
type PaymentClient struct {
	mock.Mock
}

type PaymentClient_Expecter struct {
	mock *mock.Mock
}

func (_m *PaymentClient) EXPECT() *PaymentClient_Expecter {
	return &PaymentClient_Expecter{mock: &_m.Mock}
}

// PayOrder provides a mock function for the type PaymentClient
func (_mock *PaymentClient) PayOrder(ctx context.Context, req dto.PayOrderRequest) (dto.PayOrderResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for PayOrder")
	}

	var r0 dto.PayOrderResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.PayOrderRequest) (dto.PayOrderResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.PayOrderRequest) dto.PayOrderResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Get(0).(dto.PayOrderResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, dto.PayOrderRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PaymentClient_PayOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PayOrder'
type PaymentClient_PayOrder_Call struct {
	*mock.Call
}

// PayOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - req dto.PayOrderRequest
func (_e *PaymentClient_Expecter) PayOrder(ctx any, req any) *PaymentClient_PayOrder_Call {
	return &PaymentClient_PayOrder_Call{Call: _e.mock.On("PayOrder", ctx, req)}
}

func (_c *PaymentClient_PayOrder_Call) Run(run func(ctx context.Context, req dto.PayOrderRequest)) *PaymentClient_PayOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 dto.PayOrderRequest
		if args[1] != nil {
			arg1 = args[1].(dto.PayOrderRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *PaymentClient_PayOrder_Call) Return(payOrderResponse dto.PayOrderResponse, err error) *PaymentClient_PayOrder_Call {
	_c.Call.Return(payOrderResponse, err)
	return _c
}

func (_c *PaymentClient_PayOrder_Call) RunAndReturn(run func(ctx context.Context, req dto.PayOrderRequest) (dto.PayOrderResponse, error)) *PaymentClient_PayOrder_Call {
	_c.Call.Return(run)
	return _c
}
